// Complete Applied Geography learning path data
// Generated from Obsidian markdown files

export const appliedGeographyData = {
  id: "applied-geography",
  name: "Applied Geography",
  description: "A practical curriculum for building geographic literacy",
  units: [
    // Unit 1: Foundation
    {
      id: "unit-1",
      name: "Foundation",
      completeBy: "2026-04-02",
      sections: [
        {
          id: "section-1a",
          name: "US Geography",
          code: "1A",
          deadline: "2026-02-16",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-1",
          isUnlocked: true,
          isCompleted: false,
          topics: [
            { id: "1a-t1", content: "50 states spatially (use Seterra until you can do it without hints)", completed: false },
            { id: "1a-t2", content: "Major mountain ranges: Rockies, Appalachians, Sierra Nevada, Cascades, Great Plains", completed: false },
            { id: "1a-t3", content: "Major rivers: Mississippi system (including Missouri and Ohio tributaries), Colorado, Columbia, Rio Grande", completed: false },
            { id: "1a-t4", content: "Why major cities are where they are (ports, rivers, passes, resources)", completed: false },
            { id: "1a-t5", content: "Major military installations and their geographic logic", completed: false },
            { id: "1a-t6", content: "Basic terrain of each US region: Northeast, Southeast, Midwest, Great Plains, Southwest, Pacific Northwest, Alaska, Hawaii", completed: false },
          ],
          resources: [
            { id: "1a-r1", name: "Seterra", url: "https://seterra.com", description: "Free browser-based map quizzes" },
            { id: "1a-r2", name: "Blank US maps", url: null, description: "To sketch on" },
          ],
          progressionRequirements: [
            { id: "1a-pr1", content: "Complete a blank US map quiz (all 50 states) in under 3 minutes with 100% accuracy", completed: false },
            { id: "1a-pr2", content: "Sketch from memory: Rockies, Appalachians, Sierra Nevada, Cascades, Great Plains", completed: false },
            { id: "1a-pr3", content: "Trace major river systems on a blank map", completed: false },
            {
              id: "1a-pr4",
              content: "Explain why these cities are where they are:",
              completed: false,
              children: [
                { id: "1a-pr4a", content: "New York (harbor + Hudson River access to interior)", completed: false },
                { id: "1a-pr4b", content: "Chicago (Great Lakes + rail hub + portage point)", completed: false },
                { id: "1a-pr4c", content: "New Orleans (Mississippi mouth, Gulf access)", completed: false },
                { id: "1a-pr4d", content: "Los Angeles (port, later water imported)", completed: false },
                { id: "1a-pr4e", content: "Denver (gateway to Rockies, mining supply point)", completed: false },
                { id: "1a-pr4f", content: "St. Louis (confluence of Mississippi and Missouri)", completed: false },
              ],
            },
          ],
        },
        {
          id: "section-1b",
          name: "World Regions Mental Model",
          code: "1B",
          deadline: "2026-02-28",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-1",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "1b-t1", content: "Europe regions: Western, Eastern, Nordic, Balkans, Mediterranean", completed: false },
            { id: "1b-t2", content: "Middle East regions: Gulf States, Levant, North Africa, Turkey-Iran bookends", completed: false },
            { id: "1b-t3", content: "Asia regions: East Asia, Southeast Asia, South Asia, Central Asia (the 'stans')", completed: false },
            { id: "1b-t4", content: "What makes each region a coherent grouping", completed: false },
            { id: "1b-t5", content: "Terrain signatures of each region", completed: false },
          ],
          resources: [
            { id: "1b-r1", name: "Blank world maps", url: null, description: null },
            { id: "1b-r2", name: "Seterra region quizzes", url: "https://seterra.com", description: null },
          ],
          progressionRequirements: [
            { id: "1b-pr1", content: "Draw rough boundaries around all regions listed above on a blank world map", completed: false },
            { id: "1b-pr2", content: "Explain what makes each region a coherent grouping (shared history, geography, language family, or political alignment)", completed: false },
            { id: "1b-pr3", content: "Correctly categorize any country someone names into its region without hesitation", completed: false },
            {
              id: "1b-pr4",
              content: "Describe the basic terrain signature of each region:",
              completed: false,
              children: [
                { id: "1b-pr4a", content: "Central Asia: landlocked, steppe and mountain", completed: false },
                { id: "1b-pr4b", content: "Southeast Asia: peninsular and archipelagic, tropical", completed: false },
                { id: "1b-pr4c", content: "Levant: eastern Mediterranean coast, arid", completed: false },
                { id: "1b-pr4d", content: "Nordic: cold, fjords, maritime", completed: false },
                { id: "1b-pr4e", content: "Balkans: mountainous, fragmented", completed: false },
              ],
            },
            { id: "1b-pr5", content: "Answer 'what region is between X and Y?' questions", completed: false },
          ],
        },
        {
          id: "section-1c",
          name: "Core Countries—Europe & Americas",
          code: "1C",
          deadline: "2026-03-16",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-1",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "1c-t1", content: "All 32 NATO members and their locations", completed: false },
            { id: "1c-t2", content: "EU membership vs. NATO membership overlap", completed: false },
            { id: "1c-t3", content: "Key non-NATO European states (Switzerland, Serbia, Ukraine)", completed: false },
            { id: "1c-t4", content: "Canada, Mexico, Central America, Caribbean (major countries)", completed: false },
            { id: "1c-t5", content: "Major Latin American players: Brazil, Argentina, Colombia, Chile", completed: false },
            { id: "1c-t6", content: "Five Eyes countries", completed: false },
          ],
          resources: [
            { id: "1c-r1", name: "Seterra NATO and Europe quizzes", url: "https://seterra.com", description: null },
            { id: "1c-r2", name: "Seterra Americas quizzes", url: "https://seterra.com", description: null },
          ],
          progressionRequirements: [
            { id: "1c-pr1", content: "Name all 32 NATO members and locate them on a blank map", completed: false },
            { id: "1c-pr2", content: "Identify which NATO members are also EU members, which are NATO-only, and which European countries are EU-only or neither", completed: false },
            { id: "1c-pr3", content: "Explain why NATO's eastern boundary looks the way it does", completed: false },
            { id: "1c-pr4", content: "Locate and name all countries in Central America and the Caribbean (major ones: Guatemala, Honduras, El Salvador, Nicaragua, Costa Rica, Panama, Cuba, Dominican Republic, Haiti, Jamaica)", completed: false },
            { id: "1c-pr5", content: "Name the five largest Latin American economies and locate them", completed: false },
            { id: "1c-pr6", content: "Describe Canada's population distribution and why", completed: false },
            { id: "1c-pr7", content: "Identify the Five Eyes countries and locate all of them", completed: false },
          ],
        },
        {
          id: "section-1d",
          name: "Core Countries—Middle East & Africa",
          code: "1D",
          deadline: "2026-04-02",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-1",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            {
              id: "1d-t1",
              content: "Every Middle East country: Gulf (Saudi Arabia, UAE, Qatar, Bahrain, Kuwait, Oman, Yemen, Iraq, Iran), Levant (Israel, Palestine, Jordan, Lebanon, Syria), North Africa (Egypt, Libya, Tunisia, Algeria, Morocco), Plus Turkey and Cyprus",
              completed: false,
            },
            { id: "1d-t2", content: "Gulf states in geographic order around the Persian Gulf", completed: false },
            { id: "1d-t3", content: "Countries bordering Israel and Iran", completed: false },
            { id: "1d-t4", content: "Difference between 'Middle East,' 'Arab World,' and 'Muslim World'", completed: false },
            { id: "1d-t5", content: "Key African countries: Egypt, South Africa, Nigeria, Ethiopia, Kenya, Morocco", completed: false },
            { id: "1d-t6", content: "Francophone vs. Anglophone Africa", completed: false },
          ],
          resources: [
            { id: "1d-r1", name: "Seterra Middle East and Africa quizzes", url: "https://seterra.com", description: null },
            { id: "1d-r2", name: "Blank regional maps", url: null, description: null },
          ],
          progressionRequirements: [
            { id: "1d-pr1", content: "Label every country in the Middle East on a blank map with 100% accuracy", completed: false },
            { id: "1d-pr2", content: "Name the Gulf states in geographic order around the Persian Gulf (clockwise from Iraq)", completed: false },
            { id: "1d-pr3", content: "List every country that borders Israel", completed: false },
            { id: "1d-pr4", content: "List every country that borders Iran", completed: false },
            { id: "1d-pr5", content: "Explain the difference between 'Middle East,' 'Arab World,' and 'Muslim World'", completed: false },
            {
              id: "1d-pr6",
              content: "Locate these African countries and explain why they matter:",
              completed: false,
              children: [
                { id: "1d-pr6a", content: "Egypt (Suez, largest Arab population)", completed: false },
                { id: "1d-pr6b", content: "South Africa (regional power, economy)", completed: false },
                { id: "1d-pr6c", content: "Nigeria (largest population, oil)", completed: false },
                { id: "1d-pr6d", content: "Ethiopia (population, Nile headwaters, Horn of Africa)", completed: false },
                { id: "1d-pr6e", content: "Kenya (East African hub, US counterterror partner)", completed: false },
                { id: "1d-pr6f", content: "Morocco (Western ally, Strait of Gibraltar)", completed: false },
              ],
            },
            { id: "1d-pr7", content: "Roughly distinguish Francophone vs. Anglophone Africa on a map", completed: false },
          ],
        },
      ],
    },
    // Unit 2: Strategic Geography
    {
      id: "unit-2",
      name: "Strategic Geography",
      completeBy: "2026-06-08",
      sections: [
        {
          id: "section-2a",
          name: "Chokepoints & Trade Routes",
          code: "2A",
          deadline: "2026-04-16",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-2",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "2a-t1", content: "The big 5 chokepoints: Hormuz, Suez, Malacca, Bab el-Mandeb, Panama", completed: false },
            { id: "2a-t2", content: "Oil routes from Gulf to Europe, Asia, US", completed: false },
            { id: "2a-t3", content: "South China Sea: what's contested and why", completed: false },
            { id: "2a-t4", content: "Consequences of chokepoint blockages", completed: false },
            { id: "2a-t5", content: "Russia's warm-water port problem", completed: false },
          ],
          resources: [
            { id: "2a-r1", name: "Prisoners of Geography by Tim Marshall", url: null, description: "Chokepoint chapters" },
            { id: "2a-r2", name: "CaspianReport YouTube channel", url: "https://youtube.com/@CaspianReport", description: null },
          ],
          progressionRequirements: [
            {
              id: "2a-pr1",
              content: "Locate on a blank map and explain the strategic importance of:",
              completed: false,
              children: [
                { id: "2a-pr1a", content: "Strait of Hormuz (what % of global oil, who controls each side)", completed: false },
                { id: "2a-pr1b", content: "Suez Canal (connects what to what, who controls it, recent disruptions)", completed: false },
                { id: "2a-pr1c", content: "Strait of Malacca (what trade flows through, which countries border it)", completed: false },
                { id: "2a-pr1d", content: "Bab el-Mandeb (where it is, connection to Yemen conflict and Red Sea shipping)", completed: false },
                { id: "2a-pr1e", content: "Panama Canal (who built it, who controls it now, why it matters for US Navy)", completed: false },
              ],
            },
            { id: "2a-pr2", content: "Trace on a map the route oil takes from the Persian Gulf to: Western Europe, China/Japan, United States", completed: false },
            { id: "2a-pr3", content: "Explain why the South China Sea is contested: which countries claim what, where the shipping lanes run, what the 'nine-dash line' is", completed: false },
            { id: "2a-pr4", content: "Describe what happens to global trade if any one of these chokepoints is blocked", completed: false },
            { id: "2a-pr5", content: "Explain why Russia wants warm-water ports and where they've sought them historically", completed: false },
          ],
        },
        {
          id: "section-2b",
          name: "Asia-Pacific",
          code: "2B",
          deadline: "2026-05-04",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-2",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "2b-t1", content: "All East and Southeast Asian countries", completed: false },
            { id: "2b-t2", content: "First Island Chain and Second Island Chain concepts", completed: false },
            { id: "2b-t3", content: "Rough distances: Taiwan to China, Japan to Korea, Guam to Taiwan, Darwin to Jakarta", completed: false },
            { id: "2b-t4", content: "ASEAN members", completed: false },
            { id: "2b-t5", content: "Taiwan's strategic significance", completed: false },
            { id: "2b-t6", content: "India-Pakistan-China triangle and disputed territories", completed: false },
            { id: "2b-t7", content: "Australia's geographic position and alliance logic", completed: false },
            { id: "2b-t8", content: "Quad countries", completed: false },
          ],
          resources: [
            { id: "2b-r1", name: "Prisoners of Geography", url: null, description: "Asia chapters" },
            { id: "2b-r2", name: "Peter Zeihan YouTube", url: "https://youtube.com/@PeterZeihan", description: "Videos on Asia-Pacific" },
          ],
          progressionRequirements: [
            { id: "2b-pr1", content: "Locate all East and Southeast Asian countries on a blank map", completed: false },
            { id: "2b-pr2", content: "Explain the First Island Chain and Second Island Chain concepts and why they matter for US-China strategy", completed: false },
            { id: "2b-pr3", content: "State rough distances: Taiwan to mainland China, Japan to Korea, Guam to Taiwan, Darwin to Jakarta", completed: false },
            { id: "2b-pr4", content: "List all ASEAN members and locate them", completed: false },
            { id: "2b-pr5", content: "Explain Taiwan's strategic significance (semiconductor manufacturing, geography, symbolic/political importance)", completed: false },
            { id: "2b-pr6", content: "Describe the India-Pakistan-China triangle: shared borders, disputed territories (Kashmir, Aksai Chin, Arunachal Pradesh)", completed: false },
            { id: "2b-pr7", content: "Explain why Australia's geography makes it both secure and anxious", completed: false },
            { id: "2b-pr8", content: "Identify the Quad countries and their geographic positions", completed: false },
          ],
        },
        {
          id: "section-2c",
          name: "Russia, Eastern Europe & Central Asia",
          code: "2C",
          deadline: "2026-05-20",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-2",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "2c-t1", content: "Russia's fundamental geographic challenges", completed: false },
            { id: "2c-t2", content: "Baltic states and the Suwalki Gap", completed: false },
            { id: "2c-t3", content: "Ukraine's strategic geography", completed: false },
            { id: "2c-t4", content: "The five Central Asian 'stans' and their Soviet history", completed: false },
            { id: "2c-t5", content: "Caucasus countries: Georgia, Armenia, Azerbaijan", completed: false },
            { id: "2c-t6", content: "Russia's terrain and population distribution", completed: false },
            { id: "2c-t7", content: "Kaliningrad", completed: false },
          ],
          resources: [
            { id: "2c-r1", name: "Prisoners of Geography", url: null, description: "Russia chapter" },
            { id: "2c-r2", name: "CaspianReport videos", url: "https://youtube.com/@CaspianReport", description: "Central Asia and Caucasus" },
          ],
          progressionRequirements: [
            { id: "2c-pr1", content: "Describe Russia's fundamental geographic problem (huge territory, few natural barriers to the west, limited warm-water port access)", completed: false },
            { id: "2c-pr2", content: "Locate and name the Baltic states and explain the Suwalki Gap", completed: false },
            { id: "2c-pr3", content: "Explain why Ukraine's geography makes it strategically critical", completed: false },
            { id: "2c-pr4", content: "Name and locate the five Central Asian 'stans' and identify which were Soviet", completed: false },
            { id: "2c-pr5", content: "Explain why Central Asia matters (between Russia and China, energy resources, landlocked buffer zone)", completed: false },
            { id: "2c-pr6", content: "Locate the Caucasus countries and explain the Nagorno-Karabakh conflict in geographic terms", completed: false },
            { id: "2c-pr7", content: "Describe where people actually live in Russia, what Siberia is, why the Far East is sparsely populated", completed: false },
            { id: "2c-pr8", content: "Explain what Kaliningrad is and why it's geographically unusual", completed: false },
          ],
        },
        {
          id: "section-2d",
          name: "Resources & Economic Geography",
          code: "2D",
          deadline: "2026-06-08",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-2",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "2d-t1", content: "Top oil-producing and oil-consuming countries", completed: false },
            { id: "2d-t2", content: "Oil vs. natural gas transport (tankers, pipelines, LNG)", completed: false },
            { id: "2d-t3", content: "European gas pipelines and post-2022 energy shift", completed: false },
            { id: "2d-t4", content: "Semiconductor supply chain geography (Taiwan, South Korea, Netherlands)", completed: false },
            { id: "2d-t5", content: "Rare earth deposits and China's dominance", completed: false },
            { id: "2d-t6", content: "Top agricultural exporters and Ukraine's role", completed: false },
            { id: "2d-t7", content: "Food security geography: vulnerable regions", completed: false },
            { id: "2d-t8", content: "The Sahel", completed: false },
          ],
          resources: [
            { id: "2d-r1", name: "The Accidental Superpower by Peter Zeihan", url: null, description: null },
            { id: "2d-r2", name: "Peter Zeihan YouTube", url: "https://youtube.com/@PeterZeihan", description: "Energy and demographics" },
          ],
          progressionRequirements: [
            { id: "2d-pr1", content: "Name the top 5 oil-producing countries and top 5 oil-consuming countries", completed: false },
            { id: "2d-pr2", content: "Explain the difference between oil and natural gas transport and why this matters geopolitically", completed: false },
            { id: "2d-pr3", content: "Trace major gas pipelines to Europe and explain Europe's post-2022 energy shift", completed: false },
            { id: "2d-pr4", content: "Explain why semiconductor supply chains are concentrated and why this is a strategic vulnerability", completed: false },
            { id: "2d-pr5", content: "Locate major rare earth deposits and explain China's dominance", completed: false },
            { id: "2d-pr6", content: "Name the top agricultural exporters and explain why Ukraine's production matters globally", completed: false },
            { id: "2d-pr7", content: "Explain food security geography: which regions are net importers and vulnerable", completed: false },
            { id: "2d-pr8", content: "Describe what the Sahel is and why it's geopolitically unstable", completed: false },
          ],
        },
      ],
    },
    // Unit 3: Depth
    {
      id: "unit-3",
      name: "Depth",
      completeBy: "2026-08-10",
      sections: [
        {
          id: "section-3a",
          name: "Middle East Deep Dive",
          code: "3A",
          deadline: "2026-06-29",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-3",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "3a-t1", content: "Sunni-majority vs. Shia-majority areas across the Middle East", completed: false },
            { id: "3a-t2", content: "Saudi-Iran rivalry and proxy conflicts", completed: false },
            { id: "3a-t3", content: "US military facilities in the Gulf region", completed: false },
            { id: "3a-t4", content: "Iraq's internal geographic divisions", completed: false },
            { id: "3a-t5", content: "Yemen conflict geography", completed: false },
            { id: "3a-t6", content: "Lebanon's geography and instability", completed: false },
            { id: "3a-t7", content: "Golan Heights", completed: false },
            { id: "3a-t8", content: "West Bank geography", completed: false },
          ],
          resources: [
            { id: "3a-r1", name: "CaspianReport", url: "https://youtube.com/@CaspianReport", description: "Middle East videos" },
            { id: "3a-r2", name: "Current news analysis", url: null, description: "With geographic lens" },
          ],
          progressionRequirements: [
            { id: "3a-pr1", content: "Draw a rough map showing Sunni-majority vs. Shia-majority areas (including within Iraq and Lebanon)", completed: false },
            { id: "3a-pr2", content: "Explain the Saudi-Iran rivalry: what it's about, where proxy conflicts play out (Yemen, Lebanon, Iraq, Syria)", completed: false },
            { id: "3a-pr3", content: "Name every US military facility or significant presence in the Gulf region and explain location choices", completed: false },
            { id: "3a-pr4", content: "Describe Iraq's internal geographic divisions (Kurdish north, Sunni center, Shia south)", completed: false },
            { id: "3a-pr5", content: "Explain the Yemen conflict: who the Houthis are, who backs whom, why Bab el-Mandeb matters", completed: false },
            { id: "3a-pr6", content: "Describe why Lebanon's geography and demographics make it perpetually unstable", completed: false },
            { id: "3a-pr7", content: "Explain the Golan Heights: where they are, why Israel holds them, military significance", completed: false },
            { id: "3a-pr8", content: "Describe the West Bank's geography and why settlement locations matter", completed: false },
          ],
        },
        {
          id: "section-3b",
          name: "US Military Geography",
          code: "3B",
          deadline: "2026-07-13",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-3",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "3b-t1", content: "Six geographic combatant commands: CENTCOM, EUCOM, INDOPACOM, AFRICOM, SOUTHCOM, NORTHCOM", completed: false },
            { id: "3b-t2", content: "Why command boundaries are drawn where they are", completed: false },
            { id: "3b-t3", content: "Key bases: Diego Garcia, Guam, Okinawa, Ramstein, Al Udeid, Bahrain", completed: false },
            { id: "3b-t4", content: "Tyranny of distance in the Pacific", completed: false },
            { id: "3b-t5", content: "Prepositioning", completed: false },
            { id: "3b-t6", content: "US troop presence in Japan and Germany", completed: false },
          ],
          resources: [
            { id: "3b-r1", name: "DoD public information", url: null, description: "Combatant commands" },
            { id: "3b-r2", name: "Military analysis websites and podcasts", url: null, description: null },
          ],
          progressionRequirements: [
            { id: "3b-pr1", content: "Draw rough boundaries of all six geographic combatant commands on a world map", completed: false },
            { id: "3b-pr2", content: "Explain why the command boundaries are drawn where they are (including oddities like Egypt in CENTCOM)", completed: false },
            {
              id: "3b-pr3",
              content: "Locate and explain the strategic role of:",
              completed: false,
              children: [
                { id: "3b-pr3a", content: "Diego Garcia (Indian Ocean, bomber range to Gulf and Asia)", completed: false },
                { id: "3b-pr3b", content: "Guam (Western Pacific power projection)", completed: false },
                { id: "3b-pr3c", content: "Okinawa (proximity to Taiwan and Korea)", completed: false },
                { id: "3b-pr3d", content: "Ramstein (European logistics hub)", completed: false },
                { id: "3b-pr3e", content: "Al Udeid, Qatar (CENTCOM forward HQ)", completed: false },
                { id: "3b-pr3f", content: "Bahrain (Fifth Fleet)", completed: false },
              ],
            },
            { id: "3b-pr4", content: "Explain 'tyranny of distance' in the Pacific", completed: false },
            { id: "3b-pr5", content: "Describe what prepositioning means and where the US does it", completed: false },
            { id: "3b-pr6", content: "Explain why Japan and Germany host so many US troops", completed: false },
          ],
        },
        {
          id: "section-3c",
          name: "Historical Context That Explains Today",
          code: "3C",
          deadline: "2026-07-30",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-3",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "3c-t1", content: "Ottoman Empire: territory and post-WWI collapse", completed: false },
            { id: "3c-t2", content: "Sykes-Picot and artificial Middle East borders", completed: false },
            { id: "3c-t3", content: "Cold War geographic logic: NATO vs. Warsaw Pact, containment", completed: false },
            { id: "3c-t4", content: "Decolonization's effect on African borders", completed: false },
            { id: "3c-t5", content: "Partition of India and Kashmir dispute", completed: false },
            { id: "3c-t6", content: "The 'stans' before and after USSR", completed: false },
            { id: "3c-t7", content: "Division of Germany and Berlin", completed: false },
            { id: "3c-t8", content: "Breakup of Yugoslavia", completed: false },
          ],
          resources: [
            { id: "3c-r1", name: "Prisoners of Geography", url: null, description: "Historical context sections" },
            { id: "3c-r2", name: "YouTube explainers", url: null, description: "MapMen, RealLifeLore" },
          ],
          progressionRequirements: [
            { id: "3c-pr1", content: "Explain what the Ottoman Empire was, roughly what territory it covered, and what happened to it after WWI", completed: false },
            { id: "3c-pr2", content: "Describe Sykes-Picot: what it was, why borders look artificial in the Middle East", completed: false },
            { id: "3c-pr3", content: "Explain the Cold War's geographic logic: NATO vs. Warsaw Pact, containment, battleground countries", completed: false },
            { id: "3c-pr4", content: "Describe decolonization's effect on borders in Africa", completed: false },
            { id: "3c-pr5", content: "Explain the partition of India and why Kashmir remains disputed", completed: false },
            { id: "3c-pr6", content: "Describe what the 'stans' were before the USSR collapsed and what happened after", completed: false },
            { id: "3c-pr7", content: "Explain why Germany was divided and why Berlin was particularly complicated", completed: false },
            { id: "3c-pr8", content: "Describe the breakup of Yugoslavia and why the Balkans remain complicated", completed: false },
          ],
        },
        {
          id: "section-3d",
          name: "Buffer & Consolidation",
          code: "3D",
          deadline: "2026-08-10",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-3",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "3d-t1", content: "Comprehensive review of Units 1-3", completed: false },
            { id: "3d-t2", content: "Apply geographic reasoning to current news", completed: false },
            { id: "3d-t3", content: "Identify and address weak areas", completed: false },
            { id: "3d-t4", content: "Practice teaching/explaining key concepts", completed: false },
          ],
          resources: [],
          progressionRequirements: [
            { id: "3d-pr1", content: "Pass a comprehensive self-test covering Units 1-3 (blank map quizzes, short-answer explanations)", completed: false },
            { id: "3d-pr2", content: "Explain a current news story from each region using geographic reasoning", completed: false },
            { id: "3d-pr3", content: "Identify your 3 weakest areas and demonstrate improvement via targeted review", completed: false },
            { id: "3d-pr4", content: "Teach someone else (or explain aloud) the strategic importance of: Hormuz, Taiwan, Ukraine, the Suwalki Gap, and the Gulf", completed: false },
          ],
        },
      ],
    },
    // Unit 4: Integration & Curiosity
    {
      id: "unit-4",
      name: "Integration & Curiosity",
      completeBy: "2026-09-07",
      sections: [
        {
          id: "section-4a",
          name: "Travel Geography",
          code: "4A",
          deadline: "2026-08-24",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-4",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "4a-t1", content: "Build a geographically-informed travel bucket list", completed: false },
            { id: "4a-t2", content: "Terrain and climate factors that create distinctive landscapes", completed: false },
            { id: "4a-t3", content: "US National Parks you haven't visited", completed: false },
            { id: "4a-t4", content: "Rain shadow concept and examples", completed: false },
            { id: "4a-t5", content: "Tectonic plates and where boundaries create distinctive geography", completed: false },
          ],
          resources: [
            { id: "4a-r1", name: "Google Earth terrain view", url: "https://earth.google.com", description: null },
            { id: "4a-r2", name: "Atlas Obscura", url: "https://atlasobscura.com", description: null },
            { id: "4a-r3", name: "National Geographic", url: "https://nationalgeographic.com", description: null },
          ],
          progressionRequirements: [
            { id: "4a-pr1", content: "Name 10+ places you want to visit and explain what makes each geographically distinctive", completed: false },
            {
              id: "4a-pr2",
              content: "Describe the terrain and climate factors that create these landscapes:",
              completed: false,
              children: [
                { id: "4a-pr2a", content: "Patagonia (glaciers, wind, Andes rain shadow)", completed: false },
                { id: "4a-pr2b", content: "Norwegian fjords (glacial carving)", completed: false },
                { id: "4a-pr2c", content: "New Zealand (tectonic activity, isolation)", completed: false },
                { id: "4a-pr2d", content: "Jordan's Wadi Rum (desert erosion, sandstone)", completed: false },
                { id: "4a-pr2e", content: "Iceland (volcanic, mid-Atlantic ridge)", completed: false },
              ],
            },
            { id: "4a-pr3", content: "Name 5 US National Parks you haven't visited and describe their geographic features", completed: false },
            { id: "4a-pr4", content: "Explain the concept of 'rain shadow' and identify 3 examples globally", completed: false },
            { id: "4a-pr5", content: "Describe what tectonic plates are and identify where plate boundaries create distinctive geography", completed: false },
          ],
        },
        {
          id: "section-4b",
          name: "News Integration Practice",
          code: "4B",
          deadline: "2026-09-07",
          pathId: "applied-geography",
          pathName: "Applied Geography",
          unitId: "unit-4",
          isUnlocked: false,
          isCompleted: false,
          topics: [
            { id: "4b-t1", content: "Practice applying geographic lens to any news story", completed: false },
            { id: "4b-t2", content: "Develop habit: place → locate → neighbors → terrain → strategic logic", completed: false },
            { id: "4b-t3", content: "Fill knowledge gaps independently as they arise", completed: false },
          ],
          resources: [],
          progressionRequirements: [
            {
              id: "4b-pr1",
              content: "Take any news story involving a place and, within 30 seconds, explain:",
              completed: false,
              children: [
                { id: "4b-pr1a", content: "Where it is", completed: false },
                { id: "4b-pr1b", content: "What the terrain is like", completed: false },
                { id: "4b-pr1c", content: "Who the neighbors are", completed: false },
                { id: "4b-pr1d", content: "Why geography matters to the story", completed: false },
              ],
            },
            { id: "4b-pr2", content: "Demonstrate this with 5 different stories from different regions", completed: false },
            { id: "4b-pr3", content: "Explain how you'd approach a place you've never heard of", completed: false },
            { id: "4b-pr4", content: "Identify a knowledge gap from recent news and fill it independently", completed: false },
            { id: "4b-pr5", content: "Have a 10-minute conversation about a geopolitical topic drawing on geographic reasoning throughout", completed: false },
          ],
        },
      ],
    },
  ],
}
